
[Mansions]
	#
	# Add the ID/resource location of the biome you don't want
	# RS's mansions to spawn in. Separate each ID with a comma ,
	#   Example: "minecraft:ice_spikes,awesome_mod:awesome_biome"
	blacklistedMansionBiomes = "theabyss:the_end_of_time,theabyss:the_end_of_time_2,theabyss:death,theabyss:theabyssdim,theabyss:theabyssdimiceworld,rediscovered:skylands,stacked_dimensions_warden:deeper_dark,the_legency_of_villige:pig_end,the_legency_of_villige:the_cave_world,undergarden:undergarden"
	#
	# Add Taiga Mansions to modded non-snowy Taiga biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	mansionTaigaMaxChunkDistance = 140
	#
	# Add Oak Mansions to modded forest category biomes that are not birch or dark forest.
	addMansionOakToModdedBiomes = true
	#
	# Add Taiga Mansions to modded non-snowy Taiga biomes.
	addMansionTaigaToModdedBiomes = true
	#
	# Add Snowy Mansions to modded Snowy biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	mansionSnowyMaxChunkDistance = 140
	#
	# Add Snowy Mansions to modded Snowy biomes.
	addMansionSnowyToModdedBiomes = true
	#
	# Add Birch Mansions to modded Birch biomes.
	addMansionBirchToModdedBiomes = true
	#
	# Add Oak Mansions to modded forest category biomes that are not birch or dark forest.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	mansionOakMaxChunkDistance = 140
	#
	# Add Savanna Mansions to modded Savanna biomes.
	addMansionSavannaToModdedBiomes = true
	#
	# Add Jungle Mansions to modded Jungle biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	mansionJungleMaxChunkDistance = 140
	#
	# Add Savanna Mansions to modded Savanna biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	mansionSavannaMaxChunkDistance = 140
	#
	# Add Birch Mansions to modded Birch biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	mansionBirchMaxChunkDistance = 140
	#
	# Add Jungle Mansions to modded Jungle biomes.
	addMansionJungleToModdedBiomes = true
	#
	# Add Desert Mansions to modded Desert biomes.
	addMansionDesertToModdedBiomes = true
	#
	# Add Desert Mansions to modded Desert biomes.
	# 1 for spawning in most chunks and 1001 for none.
	#Range: 1 ~ 1001
	mansionDesertMaxChunkDistance = 140

